### PR TITLE
add a translation to zh_TW.

### PR DESCRIPTION
**Pull request by rzfang**
### Goal
support zh_TW.

### Detail
* clone from the `en`.
* translate some.
* left the original english wordings that I am not sure how to translate.

### CODE REVIEW

**Comment by Morikko** [comment]
Hi rzfang, 

Can you remove the translations kept in English ? 

If a translation is not present, it falls back automatically to the English file ;)

Thank you for your work

**Comment by rzfang** [comment]
done.
please review.
thanks.

**Comment by Morikko** [comment]
Thank you, very well job :+1: 
It will be in release 0.6.5

**Comment by Morikko** [comment]
Just for curiosity did you use this [tool](https://github.com/Morikko/sync-tab-groups) I provided in the README.md ?

**Comment by rzfang** [comment]
Don't understand your question.
If you asked about `Did I use the dev version`, my answer is NO, and I just copied the file and translated the wordings what I was sure.
If you aksed about `Am I using this extension`, my answer is YES. The firefox 57 issue, you know.

**Comment by Morikko** [comment]
No sorry for the confusion, I provided a link to an online tool in my last
comment. It is a tool I created to make translation easier.

I just wanted to know if you used it or if you changed it with a text
editor. I am looking for feedback, that is the reason.

You can find some links also in the README, translation section.

**Comment by rzfang** [comment]
The `tool` link you gave is 
https://github.com/Morikko/sync-tab-groups
???

And the README `New language` link is
https://morikko.github.io/translate-web-extension/translate?headoriginal=https://github.com/Morikko/sync-tab-groups/blob/master/extension/_locales/en/messages.json
I got 404 in the first time, after I cut the url to be https://morikko.github.io/translate-web-extension, then each time I can get a fine page.
weird...

Now I know the tool, will use it.
Thanks, this really helps.

**Comment by Morikko** [comment]
I provided the wrong link for the tool :sob: 
Glad you find the good one in the README.

I understand the 404. Surprisingly, it works well on normal window but not in private window on my computer. In private window:
1. I can't fetch /translate directly https://morikko.github.io/translate-web-extension/translate
2. I should go first to https://morikko.github.io/translate-web-extension and next click to translate button

Sometimes other people complained it was down, but I not sure it is the 404 error. Maybe, it could be a Github limitation. Someone else also opened an [issue](https://github.com/Morikko/translate-web-extension/issues/2).

**Comment by Morikko** [comment]
I found a [solution](https://github.com/rafrex/spa-github-pages) to `404`. :tada:

**Pull request merged**
